apiVersion: 1

policies:
  - orgId: 1
    receiver: Email Notifications
    group_by: ["alertname", "grafana_folder", "instance"]
    group_wait: 30s
    group_interval: 5m
    # Effectively notify once until resolved; re-notify only after resolve → fire again
    repeat_interval: 8736h
