global:
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  - PrometheusText0.0.4
  evaluation_interval: 15s
runtime:
  gogc: 75
scrape_configs:
- job_name: 'node-exporter'
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - node-exporter:9100
    labels:
      instance: 'monitoring-host'
      environment: 'monitoring'
- job_name: 'prometheus'
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - localhost:9090
    labels:
      instance: 'prometheus'
      environment: 'monitoring'
- job_name: 'telemetry-host'
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - qm-telemetry.quantus.cat:443
    labels:
      instance: 'telemetry-vps'
      environment: 'production'
- job_name: 'telemetry-backend'
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - feed-telemetry.quantus.cat:443
    labels:
      instance: 'telemetry-backend'
      environment: 'production'
- job_name: heisenberg-chain
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - a1-qm-heisenberg.quantus.cat
    - a2-qm-heisenberg.quantus.cat
- job_name: heisenberg-node
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - a1-hm-heisenberg.quantus.cat
    - a2-hm-heisenberg.quantus.cat
- job_name: 'support-faucet'
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - fm-support.quantus.cat
- job_name: 'support-host'
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - hm-support.quantus.cat
- job_name: planck-subsquid-proc-1
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - PrometheusText0.0.4
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  fallback_scrape_protocol: PrometheusText0.0.4
  http_headers:
    CF-Access-Client-Id:
      files:
      - /etc/prometheus/secrets/cf_access_client_id
    CF-Access-Client-Secret:
      files:
      - /etc/prometheus/secrets/cf_access_client_secret
  static_configs:
  - targets:
    - subsquid-proc-1.quantus.com
    labels:
      chain: planck
- job_name: planck-subsquid-app-1
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - PrometheusText0.0.4
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  fallback_scrape_protocol: PrometheusText0.0.4
  http_headers:
    CF-Access-Client-Id:
      files:
      - /etc/prometheus/secrets/cf_access_client_id
    CF-Access-Client-Secret:
      files:
      - /etc/prometheus/secrets/cf_access_client_secret
  static_configs:
  - targets:
    - subsquid-app-1.quantus.com
    labels:
      chain: planck
- job_name: planck-subsquid-app-2
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - PrometheusText0.0.4
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  fallback_scrape_protocol: PrometheusText0.0.4
  http_headers:
    CF-Access-Client-Id:
      files:
      - /etc/prometheus/secrets/cf_access_client_id
    CF-Access-Client-Secret:
      files:
      - /etc/prometheus/secrets/cf_access_client_secret
  static_configs:
  - targets:
    - subsquid-app-2.quantus.com
    labels:
      chain: planck
- job_name: planck-subsquid-db-blue-1
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - PrometheusText0.0.4
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  fallback_scrape_protocol: PrometheusText0.0.4
  http_headers:
    CF-Access-Client-Id:
      files:
      - /etc/prometheus/secrets/cf_access_client_id
    CF-Access-Client-Secret:
      files:
      - /etc/prometheus/secrets/cf_access_client_secret
  static_configs:
  - targets:
    - subsquid-db-blue-1.quantus.com
    labels:
      chain: planck
- job_name: planck-subsquid-db-green-1
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - PrometheusText0.0.4
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  fallback_scrape_protocol: PrometheusText0.0.4
  http_headers:
    CF-Access-Client-Id:
      files:
      - /etc/prometheus/secrets/cf_access_client_id
    CF-Access-Client-Secret:
      files:
      - /etc/prometheus/secrets/cf_access_client_secret
  static_configs:
  - targets:
    - subsquid-db-green-1.quantus.com
    labels:
      chain: planck
- job_name: planck-subsquid-chain-1
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - PrometheusText0.0.4
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  fallback_scrape_protocol: PrometheusText0.0.4
  http_headers:
    CF-Access-Client-Id:
      files:
      - /etc/prometheus/secrets/cf_access_client_id
    CF-Access-Client-Secret:
      files:
      - /etc/prometheus/secrets/cf_access_client_secret
  static_configs:
  - targets:
    - subsquid-chain-1.quantus.com
    labels:
      chain: planck
- job_name: planck-senoti-app-1
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - PrometheusText0.0.4
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  fallback_scrape_protocol: PrometheusText0.0.4
  http_headers:
    CF-Access-Client-Id:
      files:
      - /etc/prometheus/secrets/cf_access_client_id
    CF-Access-Client-Secret:
      files:
      - /etc/prometheus/secrets/cf_access_client_secret
  static_configs:
  - targets:
    - senoti-app-1.quantus.com
    labels:
      chain: planck
- job_name: planck-senoti-db-1
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - PrometheusText0.0.4
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  fallback_scrape_protocol: PrometheusText0.0.4
  http_headers:
    CF-Access-Client-Id:
      files:
      - /etc/prometheus/secrets/cf_access_client_id
    CF-Access-Client-Secret:
      files:
      - /etc/prometheus/secrets/cf_access_client_secret
  static_configs:
  - targets:
    - senoti-db-1.quantus.com
    labels:
      chain: planck
- job_name: planck-senoti-mq-1
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - PrometheusText0.0.4
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  fallback_scrape_protocol: PrometheusText0.0.4
  http_headers:
    CF-Access-Client-Id:
      files:
      - /etc/prometheus/secrets/cf_access_client_id
    CF-Access-Client-Secret:
      files:
      - /etc/prometheus/secrets/cf_access_client_secret
  static_configs:
  - targets:
    - senoti-mq-1.quantus.com
    labels:
      chain: planck
- job_name: planck-senoti-watcher-1
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - PrometheusText0.0.4
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  fallback_scrape_protocol: PrometheusText0.0.4
  http_headers:
    CF-Access-Client-Id:
      files:
      - /etc/prometheus/secrets/cf_access_client_id
    CF-Access-Client-Secret:
      files:
      - /etc/prometheus/secrets/cf_access_client_secret
  static_configs:
  - targets:
    - senoti-watcher-1.quantus.com
    labels:
      chain: planck
- job_name: planck-senoti-core-1
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - PrometheusText0.0.4
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  fallback_scrape_protocol: PrometheusText0.0.4
  http_headers:
    CF-Access-Client-Id:
      files:
      - /etc/prometheus/secrets/cf_access_client_id
    CF-Access-Client-Secret:
      files:
      - /etc/prometheus/secrets/cf_access_client_secret
  static_configs:
  - targets:
    - senoti-core-1.quantus.com
    labels:
      chain: planck
- job_name: quersi-1
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - PrometheusText0.0.4
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  fallback_scrape_protocol: PrometheusText0.0.4
  http_headers:
    CF-Access-Client-Id:
      files:
      - /etc/prometheus/secrets/cf_access_client_id
    CF-Access-Client-Secret:
      files:
      - /etc/prometheus/secrets/cf_access_client_secret
  static_configs:
  - targets:
    - qrc-1.quantus.com
- job_name: planck-chain
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - a1-qm-planck.quantus.cat
    - a2-qm-planck.quantus.cat
- job_name: planck-node
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - a1-hm-planck.quantus.cat
    - a2-hm-planck.quantus.cat
- job_name: bootnode-chain
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - PrometheusText0.0.4
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  fallback_scrape_protocol: PrometheusText0.0.4
  http_headers:
    CF-Access-Client-Id:
      files:
      - /etc/prometheus/secrets/cf_access_client_id
    CF-Access-Client-Secret:
      files:
      - /etc/prometheus/secrets/cf_access_client_secret
  static_configs:
  - targets:
    - a1-qm-mkML2cajSbEaIYKpdo1SFexDqOUOWVy7.quantus.com
    labels:
      instance: a1
  - targets:
    - a2-qm-mkML2cajSbEaIYKpdo1SFexDqOUOWVy7.quantus.com
    labels:
      instance: a2
  - targets:
    - a3-qm-mkML2cajSbEaIYKpdo1SFexDqOUOWVy7.quantus.com
    labels:
      instance: a3
  - targets:
    - a4-qm-mkML2cajSbEaIYKpdo1SFexDqOUOWVy7.quantus.com
    labels:
      instance: a4
  - targets:
    - a5-qm-mkML2cajSbEaIYKpdo1SFexDqOUOWVy7.quantus.com
    labels:
      instance: a5
  - targets:
    - a6-qm-mkML2cajSbEaIYKpdo1SFexDqOUOWVy7.quantus.com
    labels:
      instance: a6
  - targets:
    - a7-qm-mkML2cajSbEaIYKpdo1SFexDqOUOWVy7.quantus.com
    labels:
      instance: a7
- job_name: bootnode-node
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - PrometheusText0.0.4
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  fallback_scrape_protocol: PrometheusText0.0.4
  http_headers:
    CF-Access-Client-Id:
      files:
      - /etc/prometheus/secrets/cf_access_client_id
    CF-Access-Client-Secret:
      files:
      - /etc/prometheus/secrets/cf_access_client_secret
  static_configs:
  - targets:
    - a1-hm-mkML2cajSbEaIYKpdo1SFexDqOUOWVy7.quantus.com
    labels:
      instance: a1
  - targets:
    - a2-hm-mkML2cajSbEaIYKpdo1SFexDqOUOWVy7.quantus.com
    labels:
      instance: a2
  - targets:
    - a3-hm-mkML2cajSbEaIYKpdo1SFexDqOUOWVy7.quantus.com
    labels:
      instance: a3
  - targets:
    - a4-hm-mkML2cajSbEaIYKpdo1SFexDqOUOWVy7.quantus.com
    labels:
      instance: a4
  - targets:
    - a5-hm-mkML2cajSbEaIYKpdo1SFexDqOUOWVy7.quantus.com
    labels:
      instance: a5
  - targets:
    - a6-hm-mkML2cajSbEaIYKpdo1SFexDqOUOWVy7.quantus.com
    labels:
      instance: a6
  - targets:
    - a7-hm-mkML2cajSbEaIYKpdo1SFexDqOUOWVy7.quantus.com
    labels:
      instance: a7
- job_name: rpcnode-chain
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - PrometheusText0.0.4
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  fallback_scrape_protocol: PrometheusText0.0.4
  http_headers:
    CF-Access-Client-Id:
      files:
      - /etc/prometheus/secrets/cf_access_client_id
    CF-Access-Client-Secret:
      files:
      - /etc/prometheus/secrets/cf_access_client_secret
  static_configs:
  - targets:
    - rpc1-qm-bAhQwgqf3zXDHKv6yAmetQkOalMKi1uA1.quantus.com
    labels:
      instance: rpc1
  - targets:
    - rpc2-qm-bAhQwgqf3zXDHKv6yAmetQkOalMKi1uA1.quantus.com
    labels:
      instance: rpc2
- job_name: rpcnode-node
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - PrometheusText0.0.4
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  fallback_scrape_protocol: PrometheusText0.0.4
  http_headers:
    CF-Access-Client-Id:
      files:
      - /etc/prometheus/secrets/cf_access_client_id
    CF-Access-Client-Secret:
      files:
      - /etc/prometheus/secrets/cf_access_client_secret
  static_configs:
  - targets:
    - rpc1-hm-bAhQwgqf3zXDHKv6yAmetQkOalMKi1uA1.quantus.com
    labels:
      instance: rpc1
  - targets:
    - rpc2-hm-bAhQwgqf3zXDHKv6yAmetQkOalMKi1uA1.quantus.com
    labels:
      instance: rpc2
- job_name: 'logs-host'
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - hm-logs.quantus.cat
- job_name: 'logs-graylog'
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - qm-logs.quantus.cat
