{
 "title": "Heisenberg - TXPool",
 "tags": [
  "heisenberg",
  "txpool"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "TXPool - Submitted Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "substrate_sub_txpool_submitted_transactions{job=\"heisenberg-chain\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TXPool - Block Transactions Pruned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "substrate_sub_txpool_block_transactions_pruned{job=\"heisenberg-chain\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TXPool - Block Transactions Resubmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "substrate_sub_txpool_block_transactions_resubmitted{job=\"heisenberg-chain\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TXPool - Validations Scheduled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "substrate_sub_txpool_validations_scheduled{job=\"heisenberg-chain\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TXPool - Validations Finished",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "substrate_sub_txpool_validations_finished{job=\"heisenberg-chain\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TXPool - Validations Invalid",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "substrate_sub_txpool_validations_invalid{job=\"heisenberg-chain\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}