{
 "title": "Resonance - TXPool",
 "tags": [
  "resonance",
  "txpool"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "TXPool - Finalized",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "substrate_sub_txpool_finalized_txs_total{chain=\"resonance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TXPool - submitted from mempool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "substrate_sub_txpool_submitted_from_mempool_txs_total{chain=\"resonance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TXPool - Watched",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "substrate_sub_txpool_watched_txs{chain=\"resonance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TXPool - Active views",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "substrate_sub_txpool_active_views{chain=\"resonance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}